### PR TITLE
Use a load-aware balancer

### PR DESCRIPTION
**Pull request by olix0r**
Currently, the conduit proxy uses a simplistic Round-Robin load
balancing algorithm. This strategy degrades severely when individual
endpoints exhibit abnormally high latency.

This change improves this situation somewhat by making the load balancer
aware of the number of outstanding requests to each endpoint. When nodes
exhibit high latency, they should tend to have more pending requests
than faster nodes; and the Power-of-Two-Choices node selector can be
used to distribute requests to lesser-loaded instances.

From the finagle guide:

    The algorithm randomly picks two nodes from the set of ready endpoints
    and selects the least loaded of the two. By repeatedly using this
    strategy, we can expect a manageable upper bound on the maximum load of
    any server.

    The maximum load variance between any two servers is bound by
    ln(ln(n))` where `n` is the number of servers in the cluster.

### CODE REVIEW

**Comment by deebo91** [comment]
I know that conduit is supposed to be zero config. Does this mean that conduit users are always going to have to stick with the `power_of_two_choices` load balancing?

**Comment by adleong** [comment]
Great question, @deebo91!  Power of two choices with the least loaded metrics (P2C+LL) is a very good general purpose load balancing algorithm that works pretty well for most kinds of traffic.  So I think it's a great default.  

In the future, it would be really cool to see Conduit dynamically picking an LB algorithm depending on the nature of the traffic it sees.  For example, EWMA+Latency for unary requests, P2C+LL for streaming requests, aperture when the load doesn't match the pool size, etc.

But in general, it should be possible to intelligently make these determinations based on the live data instead of needing users to configure it.

**Comment by deebo91** [comment]
That sounds like a really good feature! Aligns with the "just works" philosophy. Thanks for clarifying @adleong!

**Comment by olix0r** [comment]
ran a little test:

```
slowcooker -> lb -> hello -> world
```

_world_ is made of 9 "earth" pods with no added latency, and a single "mars" pod with 2s of added latency.

```
:; slow_cooker -concurrency=100 $HELLO
# sending 100 GET req/s with concurrency=100 to http://35.192.49.13/ ...
#                      good/b/f t   goal%   min [p50 p95 p99  p999]  max bhash change
```

p2c + pending requests (this branch)
```
2018-02-02T20:37:47Z    978/0/0 1000  97% 10s  40 [ 76  92 2075 2087 ] 2086      0 
2018-02-02T20:37:57Z    966/0/0 1000  96% 10s  40 [ 71  83 2073 2085 ] 2084      0 
2018-02-02T20:38:07Z    960/0/0 1000  96% 10s  40 [ 70  81 2075 2077 ] 2077      0 
2018-02-02T20:38:17Z    983/0/0 1000  98% 10s  40 [ 71  84 2075 2085 ] 2085      0 
2018-02-02T20:38:27Z    973/0/0 1000  97% 10s  40 [ 69  82 2071 2081 ] 2081      0 
2018-02-02T20:38:37Z    969/0/0 1000  96% 10s  40 [ 71  80 2073 2079 ] 2079      0 
2018-02-02T20:38:47Z    972/0/0 1000  97% 10s  40 [ 70  90 2075 2087 ] 2087      0 
```

round robin (v0.2.0):
```
2018-02-02T20:39:37Z    808/100/0 1000  90% 10s  39 [ 72 2069 2301 2477 ] 2476      0 
2018-02-02T20:39:47Z    909/0/0 1000  90% 10s  40 [ 67 2067 2073 2077 ] 2077      0 
2018-02-02T20:39:57Z    909/0/0 1000  90% 10s  40 [ 69 2067 2073 2079 ] 2079      0 
2018-02-02T20:40:07Z    909/0/0 1000  90% 10s  40 [ 67 2069 2079 2101 ] 2100      0 
2018-02-02T20:40:17Z    910/0/0 1000  91% 10s  40 [ 68 2067 2079 2083 ] 2083      0 
2018-02-02T20:40:27Z    907/0/0 1000  90% 10s  40 [ 66 2065 2073 2093 ] 2093      0 
2018-02-02T20:40:37Z    910/0/0 1000  91% 10s  40 [ 69 2069 2075 2077 ] 2077      0 
2018-02-02T20:40:47Z    910/0/0 1000  91% 10s  40 [ 66 2067 2075 2079 ] 2078      0 
2018-02-02T20:40:57Z    910/0/0 1000  91% 10s  40 [ 68 2069 2073 2075 ] 2075      0 
```

**Comment by seanmonstar** [comment]
Sorry for the noob question, but how I understand that results?

**Comment by klingerf** [comment]
@seanmonstar The big differentiator appears to be the improvement in p95 latency, from 2067ms to 84ms, on average. The latency columns in the output are `[p50 p95 p99  p999]`.

Another useful metric to look at is `goal%`, which represents the percentage of requests actually sent, given a goal of 100rps. The p2c output shows that it came closer to reaching the goal, which means that it had higher overall throughput.

**Comment by olix0r** [comment]
For posterity, here's the base k8s configuration i used to test the load balancing behavior https://gist.github.com/olix0r/16006b1dd98fd43221820181d36293d9

**Comment by olix0r** [comment]
@seanmonstar good question! i think the destination service should be extended to support weights; and once we've implemented that, we can introduce weighted balancing into the proxy.

**Pull request merged**
