### PR TITLE
proxy: Change `DEFAULT_OUTBOUND_ROUTER_CAPACITY` from 10,000 to 100

### PR DESCRIPTION
**Pull request by hawkw**
@olix0r wanted this changed prior to release.

### CODE REVIEW

**Comment by briansmith** [comment]
> @olix0r wanted this changed prior to release.

If it won't delay things too much, please replace this text in the commit message with the actual reasoning Oliver had for the change, for others' edification.

**Comment by briansmith** [comment]
(And by "others' edification" I mostly mean "my edification".)

**Comment by olix0r** [comment]
The proxy can't _actually_ support 10K clients currently (for one, we can't open 10K resolution streams to the destination service). 100 seems is a more-realistic but sufficiently-high default.

**Comment by hawkw** [comment]
@olix0r thanks for the answer, I was wondering that myself. Will add it to the commit message on merge.

**Pull request merged**
