### PR TITLE
proxy: Fix bench tests and require bench tests in CI

### PR DESCRIPTION
**Pull request by olix0r**
commit b197d7ba2eb847380347c03297311bd027b3a537
Author: Oliver Gould <ver@buoyant.io>
Date:   Wed May 30 02:13:18 2018 +0000

    proxy: Fix bench tests
    
    b3170af changed the DstLabels api, but the bench test was not updated
    accordingly.
    
    This updates the benches/record.rs

commit 8ca8207bbfab36c827a0615a267f5a4665dd6f8f
Author: Oliver Gould <ver@buoyant.io>
Date:   Wed May 30 02:25:36 2018 +0000

    travis: Make proxy bench tests fatal
    
    Since bench tests require a nightly rust version, we've avoided running
    them in CI. This makes it easy for these tests to break, however.
    
    If we pin the nightly version to a known-good version, we can reliably
    run these test without the fear of external changes breaking our build.

### CODE REVIEW

**Comment by seanmonstar** [comment]
I agree with @briansmith. Running benchs on Travis slows down builds dramatically. I tend to use `cargo test --benches` instead of just check, since it at least runs them once, preventing behavioral breakages from slipping in.

**Comment by olix0r** [comment]
@briansmith we're using [`cargo test --benches`](https://github.com/runconduit/conduit/pull/1038/files#diff-354f30a63fb0907d4ad57269548329e3R33) (and not `cargo bench`) for the reasons @seanmonstar mentioned: we don't waste time on a release build, but we do want to test that the benches don't immediately panic, etc.

**Comment by briansmith** [comment]
> @briansmith we're using cargo test --benches (and not cargo bench) for the reasons @seanmonstar mentioned: we don't waste time on a release build, but we do want to test that the benches don't immediately panic, etc.

I was hoping to avoid the cost of rebuilding conduit-proxy (vs type checking it) but I agree it's useful to make sure the benches don't fail dynamically too.

**Comment by olix0r** [comment]
@briansmith that's fair. the build times for this tend to be ~1minute since we can rely on cargo caching between builds. This should be even better now that we don't change nightly versions.

**Pull request merged**
