### PR TITLE
proxy: generalize histograms for reuse in TCP metrics

### PR DESCRIPTION
**Pull request by hawkw**
Depends on #763.

This PR refactors the histogram implementation in the proxy's metrics module so that it is no longer latency-specific. This will be necessary when we add TCP metrics, for the `bytes_sent` and `bytes_received` histograms.

Furthermore, I've added some tests for the histogram implementation.

### CODE REVIEW

**Comment by olix0r** [comment]
Can you please change the PR description to more clearly describe the problems with the existing implementation and what changes were made to address them?

**Comment by olix0r** [comment]
I'm not convinced that we actually need to store non-latency histograms, btw... so this may not be needed.

**Comment by hawkw** [comment]
@olix0r 
> I'm not convinced that we actually need to store non-latency histograms, btw... so this may not be needed.

If we don't want to provide histograms of bytes sent/received per connection, then this change will not be necessary. I put those metrics in the design doc in #742, but if that's not a feature we're interested in providing, it can be removed there and we can close this branch.

**Comment by hawkw** [comment]
Closing this for now, as it seems we're not going to be adding bytes sent/received histograms.

**Pull request closed without merging**
