### PR TITLE
Rewrite timing dependent tests to use mock timers

### LINKED ISSUE #412: Replace timeout.rs with tower-timeout
[`proxy/timeout.rs`](https://github.com/runconduit/conduit/blob/master/proxy/src/timeout.rs) contains an implementation of a timeout Tower middleware. `tower` also contains a [`tower-timeout`](https://github.com/tower-rs/tower/tree/master/tower-timeout) crate that does pretty much the same thing. We may want to replace our hand-rolled timeout implementation with the middleware in `tower-timeout`.

### LINKED ISSUE #455: Add mock timers for timing-dependent tests
- [x] Create a facade that abstracts over timer implementations
- [x] Modify existing code to use the timer facade
- [ ] Create a mock timer that implements the timer facade
- [ ] Rewrite time-dependent tests to use the mock timer instead

Probably depends on #412.

### LINKED ISSUE #558: Intermittent records_latency_statistics ... FAILED
The failure occurred 2 out of 5 times on my machine:

```
records_latency_statistics ... FAILED

failures:

---- records_latency_statistics stdout ----
        thread 'records_latency_statistics' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`: poorly bucketed latencies: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', tests\telemetry.rs:252:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by hawkw**
This PR continues the work I started in #480, which rewrote the `conduit_proxy::timeout` module to include a wrapper that abstracts over timer implementations, allowing us to transparently replace the default timer with a mock timer in tests. 

I've added a mock timer, and rewritten the timing-dependent tests to use it. I've also added an implementation of the timer facade for `tokio_core::reactor`'s timeouts, since we've determined that `tokio-timer`'s creation of a separate timer thread is not desirable (see https://github.com/runconduit/conduit/pull/480#issuecomment-371030804). Implementing the timer facade for a reactor handle was somewhat more complex than for `tokio-timer`, because we want to be able to configure the proxy to use that timer before the actual `Core`(s) have been instantiated. This necessitated an implementation with slightly more moving parts, but it works.

This PR supersedes #480.

Fixes #558. Fixes #412. Closes #480. Closes #455.

### CODE REVIEW

**Comment by hawkw** [comment]
It looks like some recent changes to master (cd59465366142ab3a5daf2d4973c8ce18639ce51) will make some of this code significantly easier, as `main` now owns a core, so the `LazyReactorTimer` may no longer be necessary. Let's hold off on reviewing this branch until I can rebase onto master and make some further changes.

**Comment by briansmith** [comment]
Is this blocked on something besides rebasing it on master?

**Comment by hawkw** [comment]
@briansmith I thought the code could be improved somewhat as a result of recent changes, but I looked into it and it doesn't seem that's the case --- we'll still need to set which core to use as the timer late, so that the control thread can use its' own core. I can rebase this and it should be reviewable.

**Comment by hawkw** [comment]
I am not sure whether or not we want to continue moving forwards with this, as it looks like @carllerche will be merging a timer with mocking support into `tokio` in the near future?

**Comment by briansmith** [comment]
> I am not sure whether or not we want to continue moving forwards with this, as it looks like @carllerche will be merging a timer with mocking support into tokio in the near future?

I think it would be better to fix this sooner than later because the local test failures are very annoying and we keep writing new flaky tests. OTOH I agree that it's silly to waste significant effort if we're going to have a new mockable timer soon.

**Comment by briansmith** [comment]
Anyway, if this was already working and just needs to be rebased and have merge conflicts resolved, and we expect that it will be straightforward to change it to use Tokio's mockable timers, then I'd be happy to review the rebased PR and I'd be happy to attempt to rewrite the flaky tests I'm adding to use this mocking ability instead.

**Comment by carllerche** [comment]
The new timer has been merged to Tokio master. We could depend on that initially? It would be nice to validate the new timer API works (especially for mocking) before a release is cut.

**Comment by hawkw** [comment]
Should I start a new branch to start scoping out whether @carllerche's `Tokio` changes will work for us here, then?

**Comment by hawkw** [comment]
Closing this, as when we finish the migration to the new Tokio, we'll be able to use `tokio-timer`'s mocking instead.

**Pull request closed without merging**
