### PR TITLE
WIP: Cross-compile Go executables locally, not in Docker.

### PR DESCRIPTION
**Pull request by briansmith**
Avoid all the complexity of the go-deps docker image by doing the
(cross-)compilation to Linux locally. This will reuse the results of
the `dep ensure` that everybody already runs after pulling changes
from Git. When Go 1.10 is used then its build cache will cache
dependencies in a much finer-grained way than we got with the
go-deps-based building. Since most Conduit contributors have to run
Linux-taretted Docker builds in a VM, this combination of using the
native Go execuitable + the Go 1.10 build cache should result in
substantially faster incremental rebuilds of these containers.

Expand .dockerignore so that we send even fewer files to Docker
during the build, which speeds thigns up further.

Next we can split the components of the controller into multiple
containers to further improve incremental build performance when
only a single comnponent of the controller is being modified.

Further, this is a step towards using lighter and faster container
building tools (e.g. Smith or Source-to-Image).

This should work just fine even for Go releases prior to 1.10, however
`go build` won't be incremental in those older versions.

Signed-off-by: Brian Smith <brian@briansmith.org>

### CODE REVIEW

**Comment by hawkw** [comment]
I suspect we can do a similar thing for the proxy, as well.

**Comment by briansmith** [comment]
> I suspect we can do a similar thing for the proxy, as well.

Yes, I'd like to do that too. However, the proxy, being in Rust, requires a cross-linker, which is harder to set up.

**Comment by briansmith** [comment]
> How does this change relate to the go-deps optimization in #332?

When Go 1.10 is released it will change how `go install` and `go build` cache dependencies. Some of what I did in #332 and other changes would likely need to change at last a bit for Go 1.10 in order to preserve the performance wins. #332 is a more conservative approach that's less work to finalize so I'm planning to merge #332 and then eventually (hopefully soon) replace it with this. This PR (#341) is an alternative to adjusting what is done in #332 that gets about the same performance when we switch to Go 1.10.

> Our existing Docker build setup does not require Go installed on the host system, are we ok moving away from that?

That's true, but in practice everybody hacking on the Go code in Conduit has Go installed and often (usually? almost always?) builds Conduit's Go components natively instead of using bin/docker-build*, until they need to test their changes in Kubernetes. In part this is because an edit-build-test loop using bin/docker-build* and minikube is too slow. My short-term goal is to speed up the edit-build-test loop for components that depend heavily on Kubernetes and can't work outside of Kubernetes, like the TLS infrastructure. My long-term goal is to make the edit-build-test loop using minikube so efficient that we no longer need non-Kubernetes dev environments like the docker-compose environment. 

I've already started writing a script (for Linux) that downloads exactly the right version of Go needed, verifies its sha-256, and installs it in a `conduit-tools` directory. I think this approach can be extended to other tools (e.g. the Rust tools, kubectl, minikube, etc.) and for other operating systems. We can eventually add a Git pre-submit hook that checks that the submitter has the right version of the toolchain installed.

> If a Rust developer wants the system to "just work", they'll be required to setup a Go dev environment.

Either they're hacking on the proxy and its libraries independently of the Go components, in which case this PR won't affect them, or they're using the Go components unchanged in which case they can `docker pull` the images tagged `master` and use them, or they need to modify the Go components in which case they'll probably appreciate a better edit-built-test cycle for the Go code.

> Related to 1, our Docker builds guarantee the Go version, along with the state of dependencies. With this change, we're relying on the Go version of the host system, and whether the user has run dep ensure recently. Is moving away from this an acceptable risk? Are there other ways to guarantee build consistency between contributors?

People hacking on the Go code already need to know how to do `dep ensure` at the right times already because we often avoid docker-build* in favor of building locally, for performance reasons. So I don't think `dep ensure` is a burden. We can probably add a Git pre-submit hook to check that Gopkg.lock and Gopkg.toml are consistent. We can also do a similar check in CI.

> My primary concern here is when I see a Docker image, I like to know exactly how it was built.

Yes, this is a goal for me too. I think we can get this by having a script (for Linux, at least) that downloads and installs the exact versions of the tools we need and checks the SHA-256 hashes. Then we can run that script + the build in a container (or even in a full VM) like we currently do, to generate the release images.

**Comment by briansmith** [comment]
I'm going to close this and rework things a bit, based on feedback from @siggy and @olix0r.

In the next iteration, i will make it so that one *can* compile the executables in the the images locally, without doing so in `docker build`, but the `docker build` way will still be support and still be the default.

Also, I think I'll do the next iteration of the experiment specifically for the Conduit CA containers, instead of for the entire control plane. That way my changes will be less disruptive to others. Once we've proved the concept with the Conduit CA component, we can apply it to the rest of the control plane and to the proxy.

**Pull request closed without merging**
