### PR TITLE
Abstract I/O interface into a trait.

### PR DESCRIPTION
**Pull request by briansmith**
Instead of pattern matching over an `Io` variant, use a `Box<Io>` to
abstract the I/O interface. This will make it easier to add a TLS
transport.

### CODE REVIEW

**Comment by hawkw** [comment]
@briansmith In order to review this change, I'd love some more context on why it's not sufficient to add more variants to the `Io` enum. 

Additionally, although I don't intend to base my review of this change on performance without actual measurements, I am _curious_ to hear about your intuitions are regarding the performance implications of using dynamic dispatch here.

**Comment by briansmith** [comment]
> I am curious to hear about your intuitions are regarding the performance implications of using dynamic dispatch here.

I don't think there are any notable performance implications.

**Comment by briansmith** [comment]
> why it's not sufficient to add more variants to the Io enum.

It would be sufficient.

**Comment by hawkw** [comment]
@briansmith 
> > why it's not sufficient to add more variants to the Io enum.
>
> It would be sufficient.

That's fair, I suppose I should have asked why the trait object was _preferable_ to add more variants. :)

**Comment by hawkw** [comment]
Okay, thanks for explaining the rationale behind this, @briansmith! Given that, I agree that this seems like the right approach.

**Pull request merged**
