### PR TITLE
Remove timestamps from log messages

### LINKED ISSUE #56: Proxy's logs have timestamps in an unreadable format different than what's typically used by Kubernetes
A line of output of `kubectl logs` for a conduit-proxy container looks like this:

```txt
1513399875.907490 TRCE tokio_io::framed_read ("serve", V4(127.0.0.1:4140)), attempting to decode a frame
```

The output of `kubectl logs po/kube-dns-86f6f55dd5-xzgtn dnsmasq -n kube-system` looks like this:

```txt
I1216 00:41:20.452866       1 nanny.go:108] dnsmasq[24]: using nameserver 127.0.0.1#10053 for domain ip6.arpa
```
kubedns's log is in the same format.

Notice in particular that conduit-proxy's logs's timestamps are unreadable, whereas Kuberenetes's logs's timestamps are readable. The proxy should format its timestamps like Kuberenetes does, or at least in some other more readable format.

### PR DESCRIPTION
**Pull request by hawkw**
As @olix0r requested in https://github.com/runconduit/conduit/issues/56#issuecomment-356771758, I've removed timestamps from the Conduit proxy's log records.

Closes #56

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by hawkw** [comment]
If this is something we want to do, I think it would also be pretty easy to make the proxy's log record format more closely match the format used by kube-system (like this:

```
$level      $thread $file.rs:$line] $message
````
) but I don't know if this is something we care about.

**Comment by briansmith** [comment]
> it would also be pretty easy to make the proxy's log record format more closely match the format used by kube-system

I think we should default to formatting things like other kubernetes things unless we have a reason not to. I'm not sure how consistent Kubernetes itself is in logging things in a particular format or if they have any guide to the logging format (either internally in their code or publicly).

**Comment by hawkw** [comment]
@briansmith after commit b5855357e82069352e4caa845919228eb1079eb2, the proxy's log records are formatted like this:
```
E	proxy/src/config.rs:194] conduit_proxy::config: CONDUIT_PROXY_CONTROL_URL is not set
```

Which is essentially an attempt to replicate the kube-dns style logs you mentioned in #56, though with the timestamp removed as @olix0r requested. 

> I'm not sure how consistent Kubernetes itself is in logging things in a particular format or if they have any guide to the logging format (either internally in their code or publicly).

I've done a small amount of looking for such a guide, but haven't found anything yet. It's quite possible something of that nature exists somewhere, though, and I just have yet to find it.

**Comment by briansmith** [comment]
@hawkw I looked at the output of `kubectl logs` for some other build-in containers and I found the following:

1. Not all logs are in the same format. For example, I see "ERROR:" instead of "E" at the beginning of some lines for some containers.
2. I see "E0220" and "I0220" where "0220" are some kind of counter. (If I stop minikube and restart minikube then the counter increments, I guess). Maybe this is the PID or similar?

Regardless, it seems to me like we're not getting much by abbreviating the message type to a single letter: we're consistent with nothing, really.

I think, instead, we should limit this PR to the first two commits that were already approved, and then drop the third one unless/until we can find some actual documented conventions to follow. I think, actually, that Kuberentes doesn't expect any particular format and that we might need to supply a fluentd configuration file or similar to help people parse our logs. But, that's way out of scope of this timestamp issue.

**Comment by hawkw** [comment]
@briansmith 
> I think, instead, we should limit this PR to the first two commits that were already approved, and then drop the third one unless/until we can find some actual documented conventions to follow.

Sounds good, I'll hold off on the additional changes in formatting for now.

**Comment by briansmith** [comment]
Note that in the PR description you have "Closes #10" but I think you meant "Closes #56".

**Comment by hawkw** [comment]
@briansmith oops, you're right, thanks!

**Pull request merged**
