### PR TITLE
Proxy: Sketch the watch mechanism for TLS clients.

### PR DESCRIPTION
**Pull request by briansmith**
Signed-off-by: Brian Smith <brian@briansmith.org>

### CODE REVIEW

**Comment by briansmith** [comment]
@hawkw This is the ugly stuff I was talking about. Do you have any suggestions for cleaning it up?

**Comment by hawkw** [comment]
@briansmith I _think_ I can see a way around some of the ugliness here, but let me make sure it actually compiles first :)

**Comment by briansmith** [comment]
Closing this in favor of #1087.

**Comment by hawkw** [comment]
Okay, I'll change the PR for #1087 to be based on master and give it a better commit message before merging.

**Pull request closed without merging**
